version: '3.1'

services:

  letsencrypt-nginx-container:
    container_name: 'letsencrypt-nginx-container'
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt-site:/usr/share/nginx/html
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/totsob.xyz/fullchain.pem:/etc/letsencrypt/live/totsob.xyz/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/totsob.xyz/privkey.pem:/etc/letsencrypt/live/totsob.xyz/privkey.pem
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - docker-network

  test4-sub-a:
    image: nginx:latest
    container_name: test4-con-a
    ports:
      - "8081:80"
    volumes:
      - ./web/a:/usr/share/nginx/html
      - ./webconfig/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      VIRTUAL_HOST: 'a.totsob.xyz'
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
